{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx-redirect.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "nginx-redirect.name" . }}
    chart: {{ template "nginx-redirect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
